package handler

// teamFlags maps football-data.org team names to Unicode emoji flags.
// Covers all 48 WC 2026 participants plus common name variants.
var teamFlags = map[string]string{
	// CONCACAF
	"United States":          "🇺🇸",
	"USA":                    "🇺🇸",
	"Mexico":                 "🇲🇽",
	"Canada":                 "🇨🇦",
	"Panama":                 "🇵🇦",
	"Costa Rica":             "🇨🇷",
	"Honduras":               "🇭🇳",
	"Jamaica":                "🇯🇲",
	"El Salvador":            "🇸🇻",
	"Trinidad and Tobago":    "🇹🇹",
	"Cuba":                   "🇨🇺",
	"Haiti":                  "🇭🇹",
	"Guatemala":              "🇬🇹",

	// CONMEBOL
	"Brazil":                 "🇧🇷",
	"Argentina":              "🇦🇷",
	"Colombia":               "🇨🇴",
	"Uruguay":                "🇺🇾",
	"Ecuador":                "🇪🇨",
	"Venezuela":              "🇻🇪",
	"Chile":                  "🇨🇱",
	"Paraguay":               "🇵🇾",
	"Peru":                   "🇵🇪",
	"Bolivia":                "🇧🇴",

	// UEFA
	"France":                 "🇫🇷",
	"Germany":                "🇩🇪",
	"Spain":                  "🇪🇸",
	"England":                "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
	"Portugal":               "🇵🇹",
	"Netherlands":            "🇳🇱",
	"Belgium":                "🇧🇪",
	"Italy":                  "🇮🇹",
	"Poland":                 "🇵🇱",
	"Switzerland":            "🇨🇭",
	"Austria":                "🇦🇹",
	"Croatia":                "🇭🇷",
	"Denmark":                "🇩🇰",
	"Serbia":                 "🇷🇸",
	"Scotland":               "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
	"Turkey":                 "🇹🇷",
	"Ukraine":                "🇺🇦",
	"Hungary":                "🇭🇺",
	"Slovakia":               "🇸🇰",
	"Romania":                "🇷🇴",
	"Czech Republic":         "🇨🇿",
	"Czechia":                "🇨🇿",
	"Albania":                "🇦🇱",
	"Slovenia":               "🇸🇮",
	"Georgia":                "🇬🇪",
	"Wales":                  "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
	"Greece":                 "🇬🇷",
	"Norway":                 "🇳🇴",
	"Sweden":                 "🇸🇪",
	"Finland":                "🇫🇮",
	"Iceland":                "🇮🇸",
	"North Macedonia":        "🇲🇰",
	"Bosnia and Herzegovina": "🇧🇦",
	"Kosovo":                 "🇽🇰",
	"Ireland":                "🇮🇪",

	// CAF
	"Morocco":                "🇲🇦",
	"Senegal":                "🇸🇳",
	"Cameroon":               "🇨🇲",
	"Egypt":                  "🇪🇬",
	"Nigeria":                "🇳🇬",
	"Côte d'Ivoire":          "🇨🇮",
	"Ivory Coast":            "🇨🇮",
	"Mali":                   "🇲🇱",
	"Algeria":                "🇩🇿",
	"Tunisia":                "🇹🇳",
	"Ghana":                  "🇬🇭",
	"Congo DR":               "🇨🇩",
	"DR Congo":               "🇨🇩",
	"South Africa":           "🇿🇦",
	"Tanzania":               "🇹🇿",
	"Zambia":                 "🇿🇲",
	"Uganda":                 "🇺🇬",
	"Cape Verde":             "🇨🇻",
	"Mozambique":             "🇲🇿",
	"Burkina Faso":           "🇧🇫",

	// AFC
	"Japan":                  "🇯🇵",
	"South Korea":            "🇰🇷",
	"Korea Republic":         "🇰🇷",
	"Saudi Arabia":           "🇸🇦",
	"Australia":              "🇦🇺",
	"Iran":                   "🇮🇷",
	"Qatar":                  "🇶🇦",
	"Iraq":                   "🇮🇶",
	"Jordan":                 "🇯🇴",
	"Oman":                   "🇴🇲",
	"Uzbekistan":             "🇺🇿",
	"Indonesia":              "🇮🇩",
	"China PR":               "🇨🇳",
	"China":                  "🇨🇳",
	"Palestine":              "🇵🇸",
	"Bahrain":                "🇧🇭",
	"United Arab Emirates":   "🇦🇪",
	"UAE":                    "🇦🇪",
	"Kuwait":                 "🇰🇼",

	// OFC
	"New Zealand":            "🇳🇿",
}

func teamFlag(name string) string {
	return teamFlags[name]
}
